export const problemType = [
  { name: "lack of drug 1" },
  { name: "lack of drug 2" },
  { name: "lack of drug 3" },
  { name: "lack of drug 4" },
  { name: "lack of drug 5" },
  { name: "lack of drug 6" },
  { name: "lack of drug 7" },
];

export const cities = [
  "Alexandria",
  "Aswan",
  "Asyut",
  "Bani Sweif",
  "Cairo",
  "Dakahlia",
  "Damietta",
  "Eastern",
  "Fayoum",
  "Giza",
  "Ismailia",
  "Kafr El Sheikh",
  "the lake",
  "Luxor",
  "Matrouh",
  "Minya",
  "Menoufia",
  "the new Valley",
  "North Sinai",
  "Port Said",
  "Qalyubia",
  "Qena",
  "The Red Sea",
  "Sohag",
  "South Sinai",
  "Suez",
  "Western",
];
